version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"       # Acesso ao Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

  app:
    build: ./app
    ports:
      - "80:80"           # Acesso à aplicação pelo navegador
      - "5000:5000"       # (opcional) acesso direto à API Flask sem passar pelo nginx
    networks:
      - app-net

volumes:
  jenkins_home:

networks:
  app-net:
