version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root # Usar root para evitar problemas de permissão de GID no Windows
    privileged: true # Permite que o Jenkins manipule o Docker do host
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Mapeamento do socket Docker (Docker-in-Docker)
      - /var/run/docker.sock:/var/run/docker.sock 
      # Mapeamento do volume de dados do Jenkins
      - jenkins_home:/var/jenkins_home
    environment:
      # Exporta o DOCKER_HOST para o container Jenkins (necessário no Windows/Mac)
      - DOCKER_HOST=tcp://docker:2375
    # Adicione este serviço de rede especial para acessar o host Docker via TCP
    extra_hosts: 
      - "docker:host-gateway" # Permite que 'docker' resolva para o IP do seu Host/Docker Daemon
    restart: unless-stopped

volumes:
  jenkins_home: