version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.426.3-jdk17-temurin # Alterado para uma imagem LTS específica e robusta
    user: root # Usar root para evitar problemas de permissão de GID no Windows
    privileged: true # Permite que o Jenkins manipule o Docker do host
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Mapeamento do socket Docker (Docker-in-Docker)
      # Este é o método padrão e mais robusto, desde que o container Jenkins tenha o cliente Docker.
      - /var/run/docker.sock:/var/run/docker.sock 
      # Mapeamento do volume de dados do Jenkins
      - jenkins_home:/var/jenkins_home
    # Variável DOCKER_HOST removida. 
    # O Jenkins agora usará o socket mapeado /var/run/docker.sock
    # As configurações 'extra_hosts' e 'environment' para DOCKER_HOST foram removidas.
    restart: unless-stopped

volumes:
  jenkins_home:
